#!/usr/bin/env node
// Generated by LiveScript 1.3.1
var fs, path, fsExtra, browserify, fed;
fs = require('fs');
path = require('path');
fsExtra = require('fs-extra');
browserify = require('browserify');
fed = import$({
  root: '.',
  modules: []
}, JSON.parse(fs.readFileSync("package.json").toString()).frontendDependencies || {});
(fed.modules || []).map(function(obj){
  var root, info, ref$, name, version, desdir, maindir, b, srcdir;
  obj = typeof obj === 'string' ? {
    name: obj
  } : obj;
  root = path.join("node_modules", obj.name);
  info = JSON.parse(fs.readFileSync(path.join(root, "package.json")).toString());
  if (/\.\.|\//.exec(info._id)) {
    throw new Error("fedep: not supported name in module " + obj.name + ".");
  }
  ref$ = info._id.split("@"), name = ref$[0], version = ref$[1];
  desdir = path.join(fed.root, name, version);
  maindir = path.join(fed.root, name, "main");
  fsExtra.removeSync(desdir);
  fsExtra.ensureDirSync(desdir);
  if (obj.browserify) {
    b = browserify();
    b.require(obj.name);
    b.bundle().pipe(fs.createWriteStream(path.join(desdir, name + ".js")));
  } else {
    if (obj.dir) {
      srcdir = path.join(root, obj.dir);
    } else {
      srcdir = path.join(root, "dist");
      if (!fs.existsSync(srcdir)) {
        srcdir = root;
      }
    }
    fsExtra.copySync(srcdir, desdir);
  }
  return fsExtra.ensureSymlinkSync(desdir, maindir);
});
function import$(obj, src){
  var own = {}.hasOwnProperty;
  for (var key in src) if (own.call(src, key)) obj[key] = src[key];
  return obj;
}
